config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :videos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "videos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  def username
    self[:email].split('@').first
  end

end

app/models/video.rb
class Video < ApplicationRecord
  has_one_attached :content
  has_one_attached :thumbnail

  validates :title, presence: true, length: {maximum: 20}, length: {minimum: 1}
  validates :description, presence: true, length: {maximum: 200}, length: {minimum: 1} #rich text
  validates :content, presence: true,
    content_type: ['video/mp4'],
    size: { less_than: 50.megabytes, message: 'size shuld be under 50MB!' }

  validates :thumbnail, presence: true,
    content_type: ['image/png', 'image/jpg', 'image/jpeg'],
    size: { less_than: 2.megabytes, message: 'size shuld be under 2MB!' }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_action :authenticate_user!, :only => %i[ index show ]
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to video_url(@video), notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to video_url(@video), notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :description, :content, :video_thumbnail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootsVideo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/alert' %>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_alert.html.erb
<% flash.each do | name, msg | %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> d-flex flex-row-reverse justify-content-between" role="alert">
      <button aria-hidden="true" aria-label="Close" class="btn-close" data-bs-dismiss="alert" type="button"></button>
      <div class="d-flex flex-row">
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-dark" href="https://mdbootstrap.com/">Videos App</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="d-flex form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/videos/_form.html.erb
<%= form_with(model: video) do |form| %>
  <% if video.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.file_field :content %>
  </div>

  <div>
    <%= form.label :video_thumbnail, style: "display: block" %>
    <%= form.file_field :video_thumbnail %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<div id="<%= dom_id video %>">
  <p>
    <strong>Title:</strong>
    <%= video.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= video.description %>
  </p>

</div>

app/views/videos/_video_preview.html.erb
<div id="<%= dom_id video %>">
  <div class="card">
    <% if video.content.attached? %>
      <video controls="true" poster="<%= url_for video.thumbnail if video.thumbnail.present? %>" width="100%" height="300px" preload="metadata" controlslist="nodownload">
        <source src="<%= rails_blob_url(video.content) %>" type="<%= video.content.content_type %>"></source>
      </video>
    <% end %>

  <div class="card-body">
    <h5 class="card-title"><%= video.title %></h5>
    <p class="card-text"><%= video.description[..20] %></p>
    <p class="card-text"><small class="text-muted"><%= time_ago_in_words(video.created_at) %></small></p>
  </div>
</div>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render "form", video: @video %>

<br>

<div>
  <%= link_to "Show this video", @video %> |
  <%= link_to "Back to videos", videos_path %>
</div>

app/views/videos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Home</h1>

<div id="videos" class="card-group">
  <% @videos.each do |video| %>
    <%= render 'videos/video_preview', video: video %>
  <% end %>
</div>

<%= link_to "New video", new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render "form", video: @video %>

<br>

<div>
  <%= link_to "Back to videos", videos_path %>
</div>

app/views/videos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @video %>

<div>
  <% if @video.content.attached?%>
    <div>
      <video controls="true" poster="#{url_for @video.video_thumbnail if @video.video_thumbnail.present?}" width="100%" height="300px" preload="metadata" controlslist="nodownload">
        <source src="<%= rails_blob_url(@video.content) %>" type="<%= @video.content.content_type %>"></source>
      </video>
    </div>
  <% end %>
  <%= link_to "Edit this video", edit_video_path(@video) %> |
  <%= link_to "Back to videos", videos_path %>

  <%= button_to "Destroy this video", @video, method: :delete %>
</div>